- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
      - id: go-build
      - id: go-fmt
      - id: go-vet

- repo: git://github.com/golangci/golangci-lint
  rev: master
  hooks:
    - id: golangci-lint

- repo: local
  hooks:
    - id: local-tidy
    - id: local-go-test

