language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    
# Skip the installation step. Don't "go get" dependencies.
install: skip

git:
  depth: 3

env:
  global:
    - GO111MODULE=on

jobs:
  allow_failures:
    - go: master
  include:
    - &test
      stage: Test
      go: "1.11.x"
      os: "linux"
      before_script:
        - go get golang.org/x/tools/cmd/goimports
      script:
        - ./gofmt.sh
        - go vet ./...
        - go test -v -race ./...
    - <<: *test
      go: "1.12.x" 
    - <<: *test
      go: "1.13.x"
    - <<: *test
      go: "1.14.x"
    - <<: *test
      go: "1.x"   
    - <<: *test
      go: "master"

    - stage: Analysis
      name: Sonarcloud
      if: type = pull_request OR branch = master
      dist: trusty
      addons:
        sonarcloud:
          organization: "getyoti"
      script:
        # Execute tests and coverage
        - go test -json ./... > report.json
        - go test -coverprofile=coverage.out -json ./... > sonar-report.json
        # Run Sonar
        - sonar-scanner -X

