language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    
# Skip the installation step. Don't "go get" dependencies.
install: skip

git:
  depth: 3

env:
  global:
    - GO111MODULE=on

jobs:
  allow_failures:
    - go: master
  include:
    - &test
      stage: Test
      go: "1.11.x"
      os: "linux"
      before_script:
        - go get golang.org/x/tools/cmd/goimports
      script:
        - ./.travis.gofmt.sh
        - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./yotiprotoattr/*" -not -path "./yotiprotocom/*" -not -path "./yotiprotoshare/*")) <(printf "")
        # Check that go generate ./... produces a zero diff; clean up any changes afterwards.
        - go generate -x ./... && go mod tidy && git diff --exit-code; code=$?; git checkout -- .; (exit $code) 
        - go vet ./...
        - go test -v -race ./...
    - <<: *test
      go: "1.11.x"
      os: "osx"
    - <<: *test
      go: "1.12.x"
      os: "linux"
    - <<: *test
      go: "1.12.x"
      os: "osx"
    - <<: *test
      go: "1.13.x"
      os: "linux"
    - <<: *test
      go: "1.13.x"
      os: "osx"
    - <<: *test
      go: "1.x"
      os: "linux"
    - <<: *test
      go: "1.x"
      os: "osx"
    - <<: *test
      go: "master"
      os: "linux"
    - <<: *test
      go: "master"
      os: "osx"

    - stage: Analysis
      name: Sonarcloud
      if: type = pull_request OR branch = master
      dist: trusty
      addons:
        sonarcloud:
          organization: "getyoti"
      script:
        # Execute tests and coverage
        - go test -json ./... > report.json
        - go test -coverprofile=coverage.out -json ./... > sonar-report.json
        # Run Sonar
        - sonar-scanner -X

